package com.paf.piaf;


import android.util.Log;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.ForeignCollectionField;

import java.util.Objects;

@DatabaseTable(tableName = "birds")
public class Bird {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    private int id;
    @DatabaseField(unique=true, canBeNull = false, columnName = "latin")
    private String latin;
    @DatabaseField(canBeNull = false, columnName = "french")
    private String french;
    @DatabaseField(canBeNull = true, columnName = "image_path")
    private String imagePath;
    @DatabaseField(canBeNull = true, columnName = "audio_description_path")
    private String audioDescriptionPath;

    @ForeignCollectionField
    private ForeignCollection<Sound> sounds;

    Bird() {
        // needed by ormlite
    }

    public Bird(String latin, String french, String imagePath, String audioDescriptionPath) {
        this.latin = latin;
        this.french = french;
        this.imagePath = imagePath;
        this.audioDescriptionPath = audioDescriptionPath;
    }

    public String getLatin() {
        return latin;
    }

    public String getFrench() {
        return french;
    }

    public String getImagePath() {
        return imagePath;
    }

    public String getAudioDescriptionPath() {
        return audioDescriptionPath;
    }

    public ForeignCollection<Sound> getSounds() {
        return sounds;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Bird)) return false;
        Bird bird = (Bird) o;
        return id == bird.id;
    }

    public String getImageBasePath() {
        if (imagePath==null | imagePath.equals("")) {
            return "";
        } else {
            // Log.i(Bird.class.getName(),"Image path: " + imagePath);
            return imagePath.substring(0, imagePath.lastIndexOf("."));
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return french + " (" + latin + ")";
    }


}
