package com.paf.piaf;


import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

import java.util.Objects;

@DatabaseTable(tableName = "hints")
public class Hint {
    // id is generated by the database and set on the object automagically
    public final static String HINT_FIELD_NAME = "hint";
    public final static String FRAGMENT_FIELD_NAME = "fragment";
    public final static String SHOW_FIELD_NAME = "show";

    @DatabaseField(generatedId = true)
    private int id;
    @DatabaseField(canBeNull = false, columnName = HINT_FIELD_NAME)
    private String hint;
    @DatabaseField(canBeNull = false, columnName = FRAGMENT_FIELD_NAME)
    private String fragmentName;
    // check if user wants to display this hint
    @DatabaseField(canBeNull = false, columnName = SHOW_FIELD_NAME)
    private boolean show;

    Hint() {
        // needed by ormlite
    }

    public Hint(String hint, String fragmentName) {
        this.hint = hint;
        this.fragmentName = fragmentName;
        this.show = true;
    }

    public int getId() {
        return id;
    }

    public String getHint() {
        return hint;
    }

    public String getFragmentName() {
        return fragmentName;
    }

    public boolean isShow() { return show; }

    public void setShow(boolean show) {this.show = show; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Hint)) return false;
        Hint hint = (Hint) o;
        return id == hint.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return hint;
    }
}